$s = New-Object Microsoft.PowerShell.Commands.WebRequestSession
Invoke-WebRequest -Uri 'http://127.0.0.1:8000/api/csrf/' -WebSession $s -UseBasicParsing
try {
  $resp = Invoke-RestMethod -Uri 'http://127.0.0.1:8000/api/login/' -Method Post -Body (ConvertTo-Json @{username='machad0'; password='1234'}) -ContentType 'application/json' -WebSession $s -UseBasicParsing
  Write-Output $resp
} catch {
  Write-Output "Login error: $_"
}
$cookies = $s.Cookies.GetCookies('http://127.0.0.1')
$lines = @()
$lines += '# Netscape HTTP Cookie File'
$lines += '# This file was generated by PowerShell'
foreach($c in $cookies){
  $expiry = 0
  if ($c.Expires -ne [datetime]::MinValue) { $expiry = [int](([double]($c.Expires.ToUniversalTime() - [datetime]'1970-01-01').TotalSeconds)) }
  $lines += "127.0.0.1`tFALSE`t/`tFALSE`t$expiry`t$c.Name`t$c.Value"
}
Set-Content -Path 'C:\cod\Habitos\cookies.txt' -Value ($lines -join "`n") -Encoding ASCII
Write-Output 'Wrote cookies to C:\cod\Habitos\cookies.txt'
